name: CD Pipeline (Deploy to AWS)

on:
  workflow_run:
    workflows: ["CI Pipeline (Build & Test)"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::123456789012:role/GitHubAction-Deploy-Role # CHANGE THIS
        aws-region: us-east-1
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
    - name: Terraform Init & Apply
      run: |
        cd infra
        terraform init
        terraform apply -auto-approve -var="image_tag=${{ github.event.workflow_run.head_sha }}"
